[project]
name = "greet-lib"
version = "0.1.0"

dependencies = []
requires-python = "==3.12.*"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
